spring:
  datasource:
    generate-unique-name: false
    username: users
    url: jdbc:h2:./devdb

  jpa:
    hibernate:
      ddl-auto: update

  resources:
    add-mappings: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5


